### ISSUE TITLE
Match Details Page

### ISSUE THREAD

**Issue by Akoss08** [MAdem01/el-proyecte-grande-sprint-1#52]
**Description:**

When user clicks on a game "details" button, it relocates to a match details page by id and displays all available informations about the game, including the subscribed players and the field. 

**Task:**

- [ ] Create "details" button that navigates to: /matchdetails/{id}
- [ ] Create when and where box (date, time, location, price)
- [ ] Subscribed players (username, prof pic)
- [ ] Match infos box (match rules, pitch description, pitch name, pitch type)
- [ ] Add picture from database path

**inspiration:**
![Image](https://github.com/user-attachments/assets/e73151c8-6d4e-41b0-a8ad-9a4e9cea16f2)
![Image](https://github.com/user-attachments/assets/9fbb24f1-c703-4352-a7af-d710017683c0)
